function a = lassign(X, mu0, Sigma0, mu1, Sigma1)


score0 = - log(det(Sigma0)^0.5)...
    + sum((X-repmat(mu0,[1 size(X,2)]))'...
    /Sigma0.*(X-repmat(mu0,[1 size(X,2)]))',2); 

score1 = - log(det(Sigma1)^0.5)...
    + sum((X-repmat(mu1,[1 size(X,2)]))'...
    /Sigma1.*(X-repmat(mu1,[1 size(X,2)]))',2);

a = score0>score1;
end
